
# Final Project: Car Classificaton

Author: George Cherukara Joggy

---

## Basic level

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#### Read in 'cars-train.csv' and store it in a DataFrame named movies.

In [10]:
cars_training = pd.read_csv('./datasets/cars-train.csv')
cars_training.head(10)

   car_id buying  maint doors persons lug_boot safety car_class
0       1  vhigh  vhigh     2       2    small    low     unacc
1       3  vhigh  vhigh     2       2    small   high     unacc
2       4  vhigh  vhigh     2       2      med    low     unacc
3       5  vhigh  vhigh     2       2      med    med     unacc
4       7  vhigh  vhigh     2       2      big    low     unacc
5      11  vhigh  vhigh     2       4    small    med     unacc
6      12  vhigh  vhigh     2       4    small   high     unacc
7      14  vhigh  vhigh     2       4      med    med     unacc
8      15  vhigh  vhigh     2       4      med   high     unacc
9      16  vhigh  vhigh     2       4      big    low     unacc

#### Check the number of rows and columns.